CREATE TABLE DIM_DATE(
    DIM_DATE_ID INT NOT NULL,
    DT DATE,
	DAY INT,
	MONTH INT,
	QUARTER INT,
	YEAR INT,
    PRIMARY KEY(DIM_DATE_ID)
);

CREATE TABLE DIM_AGEGRP(
    DIM_AGEGRP_ID INT NOT NULL,
    AGE_GROUP TEXT,
    PRIMARY KEY(DIM_AGEGRP_ID)
);

CREATE TABLE DIM_LOCATION(
    DIM_LOCATION_ID INT NOT NULL,
    NAME TEXT,
	TYPE TEXT,
	CODE TEXT,
    PRIMARY KEY(DIM_LOCATION_ID)

);

CREATE TABLE FACT_COV_CASES(
   FACT_COV_CASES_ID INT NOT NULL,
   DIM_DATE_ID INT REFERENCES DIM_DATE(DIM_DATE_ID),
   DIM_LOCATION_ID INT REFERENCES DIM_LOCATION(DIM_LOCATION_ID),
   DIM_AGEGRP_ID INT REFERENCES DIM_AGEGRP(DIM_AGEGRP_ID),
   MALECASES INT,
   FEMALECASES INT,
   TOTALCASES INT,
   PRIMARY KEY(FACT_COV_CASES_ID)
);

-- CREATE TABLE FACT_COVID_VACCINES(
--    FACT_COVID_VACCINES_ID INT NOT NULL,
--    DIM_DATE_ID INT REFERENCES DIM_DATE(DIM_DATE_ID),
--    DIM_LOCATION_ID INT REFERENCES DIM_LOCATION(DIM_LOCATION_ID),
--    FIRSTDOSE INT,
--    SECONDDOSE INT,
--    PRIMARY KEY(FACT_COVID_VACCINES_ID)
-- );

CREATE TABLE FACT_REGN_MISCELLANEOUS(
   FACT_REGN_MISCELLANEOUS_ID INT NOT NULL,
   DIM_LOCATION_ID INT REFERENCES DIM_LOCATION(DIM_LOCATION_ID),
   ETHNICITY TEXT,
   ETHNIC_PERCENT DECIMAL(5,2),
   NO_QUAL DECIMAL(5,2),
   NQF4_ABOVE DECIMAL(5,2),
   PRIMARY KEY(FACT_REGN_MISCELLANEOUS_ID)
);



