
--Script Maintenance by: Ife, Tosin, Yomi
---------------------------------------------------------------------------------------------------------
-- Databse and Tables DDL's for Staging area
CREATE DATABASE staging;

CREATE EXTERNAL TABLE IF NOT EXISTS staging.ethnicity(
    ETHNICITY STRING,
    GEO_NAME STRING,
    GEO_CODE STRING,
    VALUE DECIMAL(5,2))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS staging.education(
    REGION STRING,
    NO_QUAL DECIMAL(5,2),
    NQF2_ABOVE DECIMAL(5,2),
    NQF3_ABOVE DECIMAL(5,2),
	NQF4_ABOVE DECIMAL(5,2))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS staging.income(
    YEAR STRING,
    COUNTY STRING,
    AGG_TOTAL_WEALTH STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS staging.cov_cases_reg_age_gen(
    AREACODE STRING,
    AREANAME STRING,
    AREATYPE STRING,
	REPORTED_DATE DATE,
	AGE STRING,
	MALECASES INT,
	FEMALECASES INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS staging.cov_vaccinations(
    AREACODE STRING,
    AREANAME STRING,
    AREATYPE STRING,
	REPORTED_DATE DATE,
	FIRSTDOSE INT,
	SECONDDOSE INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;


CREATE EXTERNAL TABLE IF NOT EXISTS staging.country_codes(
	CTRYCD STRING,
	CTRYNM STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS staging.england_codes(
    UTLACD STRING,
    UTLANM STRING,
    RGNCD STRING,
	RGNNM STRING,
	CTRYCD STRING,
	CTRYNM STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '~'
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS staging.yorkshire_codes(
    UTLACD STRING,
    UTLANM STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '~'
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE staging.DATA_VALIDITY_AUDIT
(BATCH_ID INT,
LAYER STRING,
TYPE STRING,
NAME STRING,
RECORDS_COUNT STRING,
LOAD_DATETIME TIMESTAMP)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE staging.DATA_QUALITY_AUDIT
(BATCH_ID INT,
DATABASE_NAME STRING,
TABLE_NAME STRING,
DQ_TYPE STRING,
RESULT STRING,
LOAD_DATETIME TIMESTAMP)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

---------------------------------------------------------------------------------------------------------
-- Databse and Tables DDL's for Staging area
CREATE DATABASE mart;

CREATE EXTERNAL TABLE IF NOT EXISTS mart.DIM_DATE(
    DIM_DATE_ID INT,
    DT DATE,
	DAY INT,
	MONTH INT,
	QUARTER INT,
	YEAR INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS mart.DIM_AGEGRP(
    DIM_AGEGRP_ID INT,
    AGE_GROUP STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS mart.DIM_LOCATION(
    DIM_LOCATION_ID INT,
    NAME STRING,
	TYPE STRING,
    CODE STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '~'
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS mart.FACT_COV_DEATHS_AND_VACCINES(
	FACT_COV_DEATHS_AND_VACCINES_ID INT,
    DIM_DATE_ID INT,
	DIM_LOCATION_ID INT,
    NEWDEATHS INT,
    FIRSTDOSE INT,
	SECONDDOSE INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS mart.FACT_COV_CASES(
	FACT_COV_CASES_ID INT,
    DIM_DATE_ID INT,
	DIM_LOCATION_ID INT,
	DIM_AGEGRP_ID INT,
    MALECASES INT,
	FEMALECASES INT,
	TOTALCASES INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

-- CREATE EXTERNAL TABLE IF NOT EXISTS mart.FACT_COVID_VACCINES(
-- 	FACT_COVID_VACCINES_ID INT,
--     DIM_DATE_ID INT,
-- 	DIM_LOCATION_ID INT,
--     FIRSTDOSE INT,
-- 	SECONDDOSE INT)
-- ROW FORMAT DELIMITED
-- FIELDS TERMINATED BY ','
-- STORED AS TEXTFILE;

CREATE EXTERNAL TABLE IF NOT EXISTS mart.FACT_REGN_MISCELLANEOUS(
	FACT_REGN_MISCELLANEOUS_ID INT,
	DIM_LOCATION_ID INT,
    ETHNICITY STRING,
	ETHNIC_PERCENT DECIMAL(5,2),
    NO_QUAL DECIMAL(5,2),
    NQF4_ABOVE DECIMAL(5,2))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE mart.DATA_VALIDITY_AUDIT
(BATCH_ID INT,
LAYER STRING,
TYPE STRING,
NAME STRING,
RECORDS_COUNT STRING,
LOAD_DATETIME TIMESTAMP)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE EXTERNAL TABLE mart.DATA_QUALITY_AUDIT
(BATCH_ID INT,
DATABASE_NAME STRING,
TABLE_NAME STRING,
DQ_TYPE STRING,
RESULT STRING,
LOAD_DATETIME TIMESTAMP)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;